version: "3.7"

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6479:6379

  gost:
    container_name: gost
    image: gost:latest
    ports:
      - 7007:7007
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: sh -c "sleep 5 && ./main"
