test-clear:
	go clean -testcache
	
test:
	go test -p 1 -timeout 240s -coverprofile=cover.out ./... 

test-per-dir:
	go test -p 1 -timeout 120s ./application/...
	go test -p 1 -timeout 120s ./controller/...
	go test -p 1 -timeout 120s ./database/...
	go test -p 1 -timeout 120s ./domain/...
	go test -p 1 -timeout 120s ./internal/...
	go test -p 1 -timeout 120s ./repository/...
	go test -p 1 -timeout 120s ./service/...
	go test -p 1 -timeout 120s ./tests/...

# without ./application and ./tests
test-race:
	go clean -testcache
	go test -race -timeout 120s ./controller/...
	go test -race -timeout 120s ./database/...
	go test -race -timeout 120s ./domain/...
	go test -race -timeout 120s ./internal/...
	go test -race -timeout 120s ./repository/...
	go test -race -timeout 120s ./service/...

migrate:
	go run database/migration/main.go

run:
	go run .

test-report:
	go tool cover -html cover.out -o cover.html

migrate-test-report:
	go run database/migration/main.go
	timeout 5
	go test -p 1 -timeout 240s -coverprofile=cover.out ./...
	go tool cover -html cover.out -o cover.html

# !!windows only!! run redis in background
st-redis:
	redis-server.exe --service-start