name: Go

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "*/*/*"
  pull_request:
    branches:
      - "*"
      - "*/*"
      - "*/*/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.18.x", "1.19.x", "1.20.x", "1.21.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -o main main.go
