name: Go Build

on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:
    branches:
      - "*"
      - "*/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19.x", "1.20.x", "1.21.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Verify dependencies
        run: go mod verify

      - name: Generate Self-Signed TLS Certificate
        run: |
          mkdir -p keys
          openssl req -x509 -newkey rsa:4096 -keyout keys/private.key -out keys/publickey.crt -days 365 -nodes -subj "/CN=localhost"
        working-directory: ${{ github.workspace }}

      - name: Create .env file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build
        run: go build -o main main.go
