name: Go Security

on:
  push:
    branches:
      - "*"
      - "*/*"
  pull_request:
    branches:
      - "*"
      - "*/*"

jobs:
  GoSec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2
      - name: Run GoSec Security Scanner
        uses: securego/gosec@master
